# Generated by Django 5.0.4 on 2024-04-14 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('total_number', models.IntegerField(default=0)),
                ('buy_now', models.IntegerField(default=0)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32, verbose_name='категория')),
                ('price', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=2000)),
                ('mileage', models.IntegerField(default=0)),
                ('sity', models.CharField(max_length=20, verbose_name='город')),
                ('country', models.CharField(max_length=20, verbose_name='страна')),
                ('with_photo', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=20, verbose_name='свет')),
                ('volume', models.FloatField(default=0)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='web.marka')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='web.model')),
            ],
        ),
    ]
