# Generated by Django 5.0.4 on 2024-04-15 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_model_marka_alter_model_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='marka',
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('price', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=2000)),
                ('mileage', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=20, verbose_name='город')),
                ('country', models.CharField(max_length=20, verbose_name='страна')),
                ('with_photo', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=20, verbose_name='свет')),
                ('volume', models.FloatField(default=0)),
                ('marka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marka', to='web.marka')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='web.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
