# Generated by Django 5.0.4 on 2024-04-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_category_remove_product_model_remove_product_marka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='city_en',
            field=models.CharField(max_length=20, null=True, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='car',
            name='city_ky',
            field=models.CharField(max_length=20, null=True, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='car',
            name='city_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='car',
            name='color_en',
            field=models.CharField(max_length=20, null=True, verbose_name='свет'),
        ),
        migrations.AddField(
            model_name='car',
            name='color_ky',
            field=models.CharField(max_length=20, null=True, verbose_name='свет'),
        ),
        migrations.AddField(
            model_name='car',
            name='color_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='свет'),
        ),
        migrations.AddField(
            model_name='car',
            name='country_en',
            field=models.CharField(max_length=20, null=True, verbose_name='страна'),
        ),
        migrations.AddField(
            model_name='car',
            name='country_ky',
            field=models.CharField(max_length=20, null=True, verbose_name='страна'),
        ),
        migrations.AddField(
            model_name='car',
            name='country_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='страна'),
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='carbet',
            name='number_en',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='carbet',
            name='number_ky',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='carbet',
            name='number_ru',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='carbet',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='carbet',
            name='total_number_en',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='carbet',
            name='total_number_ky',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='carbet',
            name='total_number_ru',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(max_length=20, null=True, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=20, null=True, verbose_name='свет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='country',
            field=models.CharField(max_length=20, null=True, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='volume',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='with_photo',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2000, null=True),
        ),
        migrations.AlterField(
            model_name='carbet',
            name='buy_now',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='carbet',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='carbet',
            name='number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='carbet',
            name='total_number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='marka',
            name='title',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
